### ISSUE TITLE
threshold can go positive

### ISSUE THREAD

**Issue by markifi** [ferreum/mpv-skipsilence#4]
i don't know whether this is even an issue by itself, but it is possible to set silence threshold above 0, which seems a bit silly although it doesn't hinder the operation of the lua script.

anyway if it wasn't worth a thread, apologies.

**Comment by ferreum** [comment]
This may seem silly for most usecases, but there are actually formats that allow going above 0 dB. For example the `fltp` format, which is what is used a lot for internal processing, is the 32 bit float format described [here](https://blog.zzounds.com/2023/09/21/32-bit-float-recording-what-it-is-and-how-to-use-it/):

> But if you’re using 32-bit float, the recording won’t clip because there’s a vast amount of headroom (+770 dB, to be exact) built into the recording format.

Besides playing such a file, you can try that yourself by prepending a volume boost to the to the filter graph while such a format is in use.
That may already be the case for you in mpv. It does for me, but maybe only because I'm using [easyeffects](https://github.com/wwmm/easyeffects), which I subsequently use to compress it, so it doesn't distort the output. Skipsilence also requires `fltp` when using arnndn, and I think mpv's `scaletempo2` filter also requests it.
Beware that this can make the output *_VERY_* loud if you increase the number: `af pre @vol:volume=2`
If you play with this, beware that ffmpeg's `volumedetect` filter doesn't support this format, so it can can't show above 0 dB and distorts the audio.
